name: Criterion.rs Example
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cargo bench
      - name: Generate flamegraphs
        run: cargo bench --bench add -- --profile-time 10
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: target/criterion